version: '3'

networks:
  internal:
    driver: bridge

services:
  app:
    build:
      context: .
    networks:
        - internal
    ports:
      - "5002:5000"
    environment:
      PDFACT_URL: "http://pdfact:4567/api/pdf/parse"

  pdfact:
    image: "ghcr.io/data-house/pdfact:main"
    networks:
      - internal