version: '3'

networks:
  internal:
    driver: bridge

services:
  app:
    build:
      context: .
    networks:
        - internal
    env_file:
      - .env
    ports:
      - "5002:5000"

  pdfact:
    image: "ghcr.io/data-house/pdfact:main"
    networks:
      - internal